alias nsh "nvim ~/.config/fish/config.fish"
alias c "clear"
alias py "python3"
alias n "nvim"
alias vue "nvim -R"
alias sd "xdg-open ."
alias ra "ranger"
alias o "xdg-open 2> /dev/null"
alias mybackup "save_freetube b ; echo '' && backup b"
alias findexe "find $(pwd) -type f -executable"
alias sh "history | grep"
alias gg "git pull"
alias gs "git status"
#alias gp 'source ~/.config/fish/config.fish ; bash -e git_push $(pwd)'
alias gp 'git_push_fish'
alias gc "git reset --hard && git clean -fd"
alias gm "git stash && git pull && git stash apply"
alias gb "gradle build"
alias gr "gradle run"
alias create_snap "sudo snapper -c root create --type single --cleanup-algorithm number --description 'backup_root' ; snapper -c home create --type single --cleanup-algorithm number --description 'backup_home'"
alias gitco "ssh_agent_init && echo 'yes' > /home/adrien/.ssh/state_connect"
alias dlm "py ~/.config/myscripts/download_music.py"
alias ea "eza -1 --icons"
alias eal "eza -lh --icons"
alias time_use "time_app_tracker -q daydata ; time_app_tracker -q app-pc -n 10"
alias i "helix"
alias t "ttdl --human"
alias quic_server "QLOGDIR=./qlog RUST_LOG=trace cargo run --bin quiche-server --release -- --cert apps/src/bin/cert.crt --key apps/src/bin/cert.key --listen 0.0.0.0:4433 --root ."
alias quic_client "QLOGDIR=./qlog RUST_LOG=info cargo run --bin quiche-client --release -- --no-verify https://127.0.0.1:4433/CODEOWNERS"
alias ci "chezmoi edit"
