alias o "xdg-open 2> /dev/null"
alias mybackup "save_freetube b ; echo '' && backup b"
alias sh "history | grep"
alias gg "git pull"
alias gs "git status"
alias gp git_push
alias gc "git reset --hard && git clean -fd"
alias gm "git stash && git pull && git stash apply"
alias gitco "ssh_agent_init && echo 'yes' > /home/adrien/.ssh/state_connect"
alias create_snap "sudo snapper -c root create --type single --cleanup-algorithm number --description 'backup_root' ; snapper -c home create --type single --cleanup-algorithm number --description 'backup_home'"
alias ea "eza -1 --icons"
alias eal "eza -lh --icons"
alias i helix
alias t "ttdl --human"
alias ci "chezmoi edit"
alias arch-update "arch-update -l > ~/.arch_update_log.txt ; arch-update"
