bindsym $mod+$left focus left
bindsym $mod+$down focus down
bindsym $mod+$up focus up
bindsym $mod+$right focus right

bindsym $mod+Left focus left
bindsym $mod+Down focus down
bindsym $mod+Up focus up
bindsym $mod+Right focus right

bindsym $mod+Shift+$left move left
bindsym $mod+Shift+$down move down
bindsym $mod+Shift+$up move up
bindsym $mod+Shift+$right move right

bindsym $mod+Shift+Left move left
bindsym $mod+Shift+Down move down
bindsym $mod+Shift+Up move up
bindsym $mod+Shift+Right move right

bindsym $mod+quotedbl workspace number 1
bindsym $mod+guillemotleft workspace number 2
bindsym $mod+guillemotright workspace number 3
bindsym $mod+parenleft workspace number 4
bindsym $mod+parenright workspace number 5

bindsym $mod+at move container to workspace number 1
bindsym $mod+plus move container to workspace number 2
bindsym $mod+minus move container to workspace number 3
bindsym $mod+slash move container to workspace number 4
bindsym $mod+asterisk move container to workspace number 5

bindsym $mod+b splith
bindsym $mod+v splitv

bindsym $mod+l layout stacking
bindsym $mod+w layout tabbed
bindsym $mod+e layout toggle split

bindsym $mod+f fullscreen

bindsym $mod+Shift+space floating toggle

mode "resize" {
    bindsym $left resize shrink width 20px
    bindsym $down resize grow height 20px
    bindsym $up resize shrink height 20px
    bindsym $right resize grow width 20px

    bindsym Left resize shrink width 20px
    bindsym Down resize grow height 20px
    bindsym Up resize shrink height 20px
    bindsym Right resize grow width 20px

    bindsym Return mode "default"
    bindsym Escape mode "default"
}

bindsym $mod+o mode "resize"

bindsym $mod+Return exec $term

bindsym $mod+q kill

bindsym $mod+i exec $menu

bindsym $mod+tab exec rofi -show window -display-window-icons -display-drun -theme .config/rofi/theme.rasi

bindsym $mod+Shift+x reload

bindsym $mod+j move scratchpad
bindsym $mod+n scratchpad show

bindsym $mod+z exec alacritty --class alacritty-fullscreen -e /home/adrien/.config/myscripts/openfile

bindsym $mod+p exec /home/adrien/.config/myscripts/closeApp

bindsym $mod+u exec waylock -init-color 0x000000 -input-color 0x505050 -fail-color 0xa0a0a0

bindsym $mod+space exec /home/adrien/.config/myscripts/changeKeyboard

bindsym $mod+Shift+Return exec alacritty -e nvim

bindsym $mod+Shift+m exec wl-mirror -F --fullscreen eDP-1

