mode "theme_random" {
        bindsym y exec /home/adrien/.config/myscripts/randomTheme ; mode "default"
        bindsym i exec /home/adrien/.config/myscripts/randomTheme d ; mode "default"
        bindsym x exec /home/adrien/.config/myscripts/randomTheme c ; mode "default"

        bindsym Return mode "default"
        bindsym Escape mode "default"
}

bindsym $mod+y mode "theme_random"

bindsym $mod+Shift+y exec /home/adrien/.config/myscripts/changeTheme $(ls $HOME/.config/mythemes | rofi -dmenu -theme $HOME/.config/rofi/theme.rasi)
