mode "theme" {
        bindsym a exec /home/adrien/.config/myscripts/changeTheme Cartique_spatiale  ; mode "default"
        bindsym m exec /home/adrien/.config/myscripts/changeTheme Cmontagne_colore ; mode "default"
        bindsym s exec /home/adrien/.config/myscripts/changeTheme Csoleil_aurore ; mode "default"
        bindsym r exec /home/adrien/.config/myscripts/changeTheme Croche ; mode "default"
        bindsym n exec /home/adrien/.config/myscripts/changeTheme Ccloud ; mode "default"
        bindsym f exec /home/adrien/.config/myscripts/changeTheme Cfallaisechinoise ; mode "default"
        bindsym t exec /home/adrien/.config/myscripts/changeTheme Dchalet ; mode "default"
        bindsym l exec /home/adrien/.config/myscripts/changeTheme Dlac_boreal ; mode "default"
        bindsym c exec /home/adrien/.config/myscripts/changeTheme Dcolines_spatial ; mode "default"
        bindsym d exec /home/adrien/.config/myscripts/changeTheme Ddesert_etoile ; mode "default"
        bindsym h exec /home/adrien/.config/myscripts/changeTheme Dhiver_spatial ; mode "default"
        bindsym p exec /home/adrien/.config/myscripts/changeTheme Dpanda ; mode "default"
        bindsym v exec /home/adrien/.config/myscripts/changeTheme Dplanete_violette ; mode "default"
        bindsym u exec /home/adrien/.config/myscripts/changeTheme Dunix ; mode "default"
        bindsym b exec /home/adrien/.config/myscripts/changeTheme Dciel_anime ; mode "default"

        bindsym Return mode "default"
        bindsym Escape mode "default"
}

bindsym $mod+y mode "theme"

