# Auto start apps

exec mpd

exec bluetoothctl power off

exec blueman-applet

exec nm-applet

exec fusuma

exec dunst

exec workstyle

exec /home/adrien/.config/myscripts/trashTmp

exec /home/adrien/.config/myscripts/batteriecheck

exec echo "no" > /home/adrien/.ssh/state_connect

exec systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=sway

exec /home/adrien/.config/myscripts/control_swww start

