#!/bin/bash

flag=0

if [[ "$1" = "check" ]]
then
	sleep 5
	wallpaper=$(basename $(swww query | cut -d ' ' -f8))
	if [[ ! "$wallpaper" =~ ".gif" ]]
	then
		exit
	fi
fi

while [ 1 ]
do
	apps="$(niri msg focused-window)"

	if [[ "$apps" = "No window is focused." || "$apps" =~ "Alacritty" ]]
	then
		if [ "$flag" != 1 ]
		then
			kill -SIGCONT $(pgrep -x swww-daemon)
			flag=1
		fi
	else
		if [ "$flag" != 2 ]
		then
			kill -SIGSTOP $(pgrep -x swww-daemon)
			flag=2
		fi
	fi

	sleep 5
done
