#!/bin/bash

apps=$(niri msg windows | grep "App ID:" | cut -d '"' -f2)
titles=$(niri msg windows | grep "Title:" | cut -d '"' -f2)
ids=$(niri msg windows | grep "Window ID " | awk '{print $3}' | cut -d: -f1)

choices=$(echo "$apps" | paste - <(echo "$titles"))
id=$(echo "$choices" | fuzzel -w 50 --index --dmenu)

if [ "$id" != "" ]
then
    id=$(echo "$ids" | awk -v n=$id 'NR==n+1')
    niri msg action focus-window --id "$id"
fi
