#!/bin/bash

new_theme="$1"
dir_themes="$HOME/.config/mythemes"

if [[ ! -e "$dir_themes/templates/$new_theme" ]]
then
    notify-send "Ce thème n'existe pas"
    exit 1
fi

if [ "${new_theme:0:1}" = "D" ]
then
    # général
    GTHEME="prefer-dark"
    GLOBAL_THEME="dark"
    WRITE_THEME="#f1efef"

    # swww
    WALLPAPER=dark/${new_theme:1}

    COLOR1="#000000"
    COLOR3="#000000"

elif [ "${new_theme:0:1}" = "L" ]
then
    # général
    GTHEME="prefer-light"
    GLOBAL_THEME="light"
    WRITE_THEME="#090c0c"

    # swww
    WALLPAPER=light/${new_theme:1}

    COLOR1="#ffffff"
    COLOR3="#ffffff"

else
    notify-send "Erreur de changement de thème"
    exit 2
fi

source "$dir_themes/templates/$new_theme"

COLOR2=$($HOME/.config/myscripts/hexa_middle \\$COLOR1 \\$COLOR3)

if [[ "$(chezmoi status)" = "" ]]
then
    echo "[data]
      global_theme = \"$GLOBAL_THEME\"
      write_theme = \"$WRITE_THEME\"
      color1 = \"$COLOR1\"
      color2 = \"$COLOR2\"
      color3 = \"$COLOR3\"
      alacritty_opacity = \"$OPACITETERM\"" > "$HOME/.config/chezmoi/chezmoi.toml"

    pkill -x control_swww
    kill -SIGCONT $(pgrep -x swww-daemon)

    if [[ -e "$dir_themes/wallpapers/${WALLPAPER}.gif" ]]
    then
        {
            swww img -t any "$dir_themes/wallpapers/${WALLPAPER}.gif"
            sleep 5
            $HOME/.config/myscripts/control_swww
        } &
    else
        swww img -t any "$dir_themes/wallpapers/${WALLPAPER}.png"
    fi

    niri msg action do-screen-transition --delay-ms 300

    gsettings set org.gnome.desktop.interface color-scheme "$GTHEME"
    chezmoi apply --force

    exit 0
else
    notify-send "Erreur les configurations sont différentes"
    exit 3
fi
