#!/bin/bash

#sudo nvim /etc/anacrontab
#1	5	empty_trash	/home/adrien/.config/myscripts/trashTmp

pathTrash="$HOME/.Trash"

for file in ${pathTrash}/*
do
    last_modification=$(stat -c %Y "$file")
    now=$(date +%s)
    diff=$((now - last_modification))
    diff_day=$((diff / (60 * 60 * 24)))

    if [ "$diff_day" -gt 7 ]
    then
        rm -fr "$file"
    fi
done

