#!/bin/bash

idfocus=$(swaymsg -t get_tree | jq '.. | select(.type?) | select(.focused==true).pid')
eval 'swaymsg [pid="$idfocus"] move scratchpad'

if [[ "$(swaymsg -t get_tree | grep -c pid)" = "0" ]]
then
    shutdown now
else
    response=$(zenity --question --text="Voulez-vous continuer ?" --title="Confirmation")
    if [ "$?" = 0 ]; then
        shutdown now
    fi
fi
