use-grammars = { only = [ "rust" ] }

[[language]]
name = "rust"
auto-format = true
indent = { tab-width = 4, unit = " " }
roots = [ "Cargo.toml", "Cargo.lock" ]
file-types = ["rs"]
diagnostic-severity = "hint"
language-servers = ["rust-analyzer"]

[language-server.rust-analyzer]
command = "rust-analyzer"

[language-server.rust-analyzer.config.check]
command = "clippy"
