[[language]]
name = "rust"
# auto-format = true
# indent = { tab-width = 4, unit = " " }
roots = [ "Cargo.toml", "Cargo.lock" ]
diagnostic-severity = "warning"

[language-server.rust-analyzer]
command = "rust-analyzer"

[language-server.rust-analyzer.config]
inlayHints.bindingModeHints.enable = false
inlayHints.closingBraceHints.minLines = 10
inlayHints.closureReturnTypeHints.enable = "with_block"
inlayHints.discriminantHints.enable = "fieldless"
inlayHints.lifetimeElisionHints.enable = "skip_trivial"
inlayHints.typeHints.hideClosureInitialization = false

[[language]]
name = "java"
auto-format = true
indent = { tab-width = 4, unit = " " }
roots = [ "pom.toml", "build.gradle" ]
diagnostic-severity = "warning"

[language-server.jdtls]
command = "jdtls"
