#!/bin/bash

if [[ "$1" == "restart" && "$(pgrep -x swww-daemon)" != "" ]]
then
	swww kill
	swww-daemon &
	exit 0
fi

if [[ "$1" == "stop" ]]
then
	swww kill
	pgrep -x control_swww | grep -v "$$" | xargs kill
	exit 0
fi

if [[ "$1" != "start" ]]
then
	exit 0
fi

swww-daemon &

flag=0

while [ 1 ]
do
	apps="$(swaymsg -pt get_workspaces | grep  -A 4 "focused" | grep "Representation" | cut -d ':' -f2)"
	echo $$
	echo $apps

	# if [[ "$apps" = " (null)" || "$apps" = " H[]" || "$apps" =~ "Alacritty" ]]
	# then
	# 	if [ "$flag" != 1 ]
	# 	then
	# 		kill -SIGCONT $(pgrep -x swww-daemon)
	# 		flag=1
	# 	fi
	# else
	# 	if [ "$flag" != 2 ]
	# 	then
	# 		kill -SIGSTOP $(pgrep -x swww-daemon)
	# 		flag=2
	# 	fi
	# fi

	sleep 5
done

