#!/bin/bash

time_app_tracker --state switch

if [[ "$(time_app_tracker -s | grep State | grep on)" ]]
then
  notify-send -a "Time App Tracker" "State : ON"
else
  notify-send -a "Time App Tracker" "State : OFF"
fi
